### ISSUE TITLE
all operators need to add their public keys to operator_defaults.sh

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#131]
The config/operator_defaults.sh script contains public keys used to log into various HPC machines and copy results to THREDDS servers ... to facilitate the granting of access to these resources, all Operators should put all their public keys in config/operator_defaults.sh.

**Comment by wwlwpd** [comment]
Be **very** sure not to include the private keys. I have a security concern also, but I will have to mention it private. Not that I have to give bad guys any ideas.

That asside, a default $HOME/.ssh/config file might provide some opportunity for simplifying the logic of the platform.sh or wherever the TDS servers are defined.

`Host tdd1
  Hostname <operator-specific-tdds-host-here>
  User <operator-specific-here>
  IdentityFile /path/to/<operator-specific-tdds-private-key-here>

Host tdd2
Hostname <operator-specific-tdds-host-here>
User <operator-specific-here>
IdentityFile /path/to/<operator-specific-tdds-private-key-here>

Host tdd3
Hostname <operator-specific-tdds-host-here>
User <operator-specific-here>
IdentityFile /path/to/<operator-specific-tdds-private-key-here>
`
The advantage here is all the variance is handled in the $HOME/.ssh/config, but asgs can assume that the hosts aliased by "tdd1", "tdd2", and "tdd3" above.

But for however you may utilize a standard $HOME/.ssh/config file, the option is there. I say this also because what I saw in the most recent platforms.sh reminded me very much of this nice feature of ssh and it's config file options.

**Comment by hapoo** [comment]
I have added my Public Key with pull request #145

**Comment by wwlwpd** [comment]
Here's my proposal:

1. we maintain an `authorized_hosts` file to which we add public keys (a single one, not differentiated by resource or site)
2. public keys should be a minimum strength, I don't know what to suggest immediately but I think it's not a bad idea to require that they be at least 4096 bits (i.e., created via `ssh-keygen -b 4096`)
3. public keys should be stripped of any identifying information, that's basically anything after the `==` at the end of the string; `ssh-keygen` typically adds in `$user@$hostname`; since github is public (it'd be much better if this was handled privately, however; but assuming there are eyes on this...)
4.  in addition to an authorized_keys file, we distribute an ssh config file that complements the remote resources that is to be installed into (or appened to) the $HOME/.ssh/config file where the authorized operator is needed to access the resource; this will allow us to use short names for all resources and also define all ssh options we normally need to define by virtue of using the short name; this includes: host, identity file (private key), username, and any other ssh related options we need for convenience.
5. the maintainers of remote resources can can then use the distributed authorized_keys database to add access in a pinch; the $HOME/.ssh/config file will be leveraged by ASGS to avoid having to add keys, usernames, and custom options for operators in the *code*; once installed, the operator can adjust their .ssh/config file as they see fit and ASGS will just use it so long as the short name that defines the connection doesn't change

Ideally, resource operators and operators would be able to communicate outside of a public site like GH to exchange public keys, username information, etc.

Additional advice for resource operators:
1. when creating user accounts for ssh access, I'd name them generally and keep track locally (maybe even on paper) who is generally going to be using each account to access the account
2. ALWAY disallow password access and require key access for these users (always)
3. you may wish to expire keys after some time or period of inactivity (this could cause issues DURING a season, so manage that being aware of operational needs)
4. investigate the options that sshd provides to further restrict access; in addition to keys, you can restrict access down to the IP address; this means that if you know the IP ranges of the resources that will be dumping files onto your resource, whitelist the IPs or IP ranges

I think creating a safe exchange of public keys and USE of them operationally requires a solid process, proactive security measures, and education (for all of us).  In the future, we can look at creating a database service with client tools (for operators and resource admins) to exchange this information more seemlessly and away from prying eyes.

**Comment by jasonfleming** [comment]
Hey @wwlwpd thank you for this, I have cut and pasted this into our nascent ASGS Operators Onboarding Checklist google doc. I will send you a link.

**Comment by wwlwpd** [comment]
@jasonfleming here is a demonstration of a basic ssh_config (would go in as operators `$HOME/.ssh/config`) - beware, I didn't test it but this should be mostly correct and a good start.

https://github.com/wwlwpd/asgs/commit/4068a150e2c5b16b10276ad681d7fa61c9833ac7

You'll note there's a lot of RED in the diff, indicating lots of stuff removed and ssh/scp/rsync commands (and related processings) has been greatly simplified. In addition to this, the operator may modify their $HOME/.ssh/config to suite their needs.

Summary:
eliminated: `SSHPORT`, `OPENDAPUSER`, need to manage the ssh key exlicitly
simplified: `ssh`, `scp`, and `rsync`
