### ISSUE TITLE
multiple brewed ASGSes (or none) in a single user account on HPC

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#167]
We often need to have multiple ASGSes installed on a single user account on an HPC system (e.g., 2019stable for production alongside master or a feature branch). Does asgs-brew accommodate that? Related to that, an HPC user may want to completely uninstall the ASGS, or may have other activities going on the HPC that should not use the custom python and/or perl that the ASGS environment provides, is it possible uninstall the ASGS or temporarily disable the asgs-specific environment?

**Comment by jasonfleming** [comment]
Also, asgs-brew is modifying the ~/.bash_profile ...   do different HPC machines require modifying different startup files like ~/bashrc or ~/.profile?

**Comment by jasonfleming** [comment]
How do the modules systems on these platforms interact with the environment variables set by asgs-brew? For example, if an Operator has certain modules loaded when they install, do the environment variables set by asgs-brew incorporate those PATHs, so they can't be circumvented thereafter by unloading the module?

**Comment by jasonfleming** [comment]
Does ~/.bash_profile get appended by asgs-brew or overwritten or does asgs-brew go through and rewrite the env variable settings? In other words, how to prevent collisions between asgs-brew settings and other unrelated env variable settings set by the Operator in that file?

**Comment by wwlwpd** [comment]
`~/.bash_profile` only gets updated after perlbrew is run, but I was going to remove that actually since we should direct everyone through asgsh. I'll add an issue to do that. 

Other than that, the only thing really preventing this is that `asgsh` uses a statically defined environment file. Allowing full environments side by side through a single asgsh would be a great feature.  I'll add this as another issue.

To do it manually, you'd have to rename `$HOME/.asgs-brew.sh` to not clobber, then copy `$install_path/bin/asgsh` to something like `$install_path/bin/asgshX`. And even then you'd have to avoid save profile names across all installations. So definitely a pain, but this can be added without too much work.

**Comment by wwlwpd** [comment]
Created #168 and #169. @jasonfleming is either or are both blockers for stable2019 or would you like to consider them either bug fixes or target master? I can prioritize them and it wouldn't be much work to get this working.

**Comment by wwlwpd** [comment]
Oh and `~/.bash_profile` is intelligently updated or at least there is an attempt to be smart about it.

**Comment by jasonfleming** [comment]
Ok thank you, I am still going through the installation work and would like to get comfortable with it for 2019stable before we make it official. So yes I think it is right to continue to focus on it in the immediate term.

**Comment by jasonfleming** [comment]
Also, I want to make sure we have a consistent perl/python/library environment (a) interactively on the command line; (b) across all login nodes; (c) in a screen session; (d) in an interactive batch session; and (e) in a parallel batch job. We've had issues on various platforms where invoking `screen` will strip the environment (because reasons?) and others where starting a parallel batch job strips your environment, etc. How can we ensure we are getting the environment and paths we need across these different execution environments while taking into account that different HPC machines handle this differently?

**Comment by jasonfleming** [comment]
I guess we need an onboarding document checklist for each new HPC machine to diagnose how it handles each of these execution environments...

**Comment by wwlwpd** [comment]
> Also, I want to make sure we have a consistent perl/python/library environment:

This basically means that we'll avoid using the host provided python environment. On LSU resources, this means not including any of the python "module" loads. See inline for other questions you had;

>(a) interactively on the command line;

doing everything in an asgsh session will ensure this

>(b) across all login nodes;

since all login nodes should provide the exact same experience (though we know from experience this is not always the case), I think using asgsh is key

>(c) in a screen session;

I am not that familiar with screen, so we'll have to see what experiences away us; from what I have seen for screen and tmux, the sessions adopt the environment from which they were FIRST created (e.g., pwd, etc)

>(d) in an interactive batch session; and
>(e) in a parallel batch job.

It's been my experience that the environments for interactive and for non-interactive batch jobs inherit the environment from which they were lauched; if this holds true, using asgsh when starting ASGS or submitting jobs (any) manually will be the right approach

>We've had issues on various platforms where invoking `screen` will strip the environment (because reasons?) and others where starting a parallel batch job strips your environment, etc. How can we ensure we are getting the environment and paths we need across these different execution environments while taking into account that different HPC machines handle this differently?

We need to look deeper into what screen is doing. asgsh loads all ASGS bash scripts that provide functions and other settings, for example ./platforms.sh. I suspect we'll run into some cases where there is a conflict, but the answer will be to handle the environment in ASGS scripts more consistently and with more discipline. I won't be surprised if we discover some issues, but as I said, those are opportunities to make the whole set up more consistent.

**Comment by wwlwpd** [comment]
> I guess we need an onboarding document checklist for each new HPC machine to diagnose how it handles each of these execution environments...

This is a good idea. Essentially, we're only going to be relying on the HPC node for the Intel compilers.

**Comment by wwlwpd** [comment]
My current approach is going to be something similar to the following:

1. ASGS installations should be installed "next to" each other in their own directories
2. add a "--name" parameter to asgs-brew.pl to allow the operator to name the ASGS installation; it would need to default to something, probably $$ (process id of asgs-brew.pl), which is not helpful to a human but would prevent installations from clobbering one another
3. having a "name" for the ASGS installation means that each --install-path (e.g., currently defaults to $HOME/opt) will need to default "$install_path/$name" (would default to $HOME/opt/$$)
4. asgsh currently supports saving "profiles" (used to save set ups for different configurations, but assumes a single ASGS installation) so most likely this can be extended to: create a saved profile that uses $name that contains the ENTIRE environment; from there the user would load the profile that is the "default" for that install. Then any customizations they make can be saved in additional profile without the original being affect. We'd have to provide some tutorial on this.
5. not said, but implied in 4. above is that there would be a SINGLE asgsh wrapper, but it would be able to handle the management of different profiles

The above plan would accomodate one having multiple ASGS full installations, all with their own environment, own libraries, binaries, etc. Initially, it'd be easiest to treat everything separate. Mixing and matching binaries among different installations will probably be overkill (just anticipating a potental optimization one may think to request) and I'd argue against supporting it, at least until we were able to prove initial support through heavy operational use.

**Comment by wwlwpd** [comment]
I have add this issue to the ASGS enhancements milestone, but will be treating it as a priority.

**Comment by wwlwpd** [comment]
@jasonfleming - I have started the working and with https://github.com/wwlwpd/asgs/commit/c2cd585d5f2ebac37f715d33f2f39a29ea90e0d1 asgs-brew.pl will leverage the profiles ability of asgsh to save the environment that was used to build everything.

Questions:
1. perl is already "global" by virtue of how we're using perlbrew; I can make the python install "global" also very easily, any potential conflict in doing so? I don't see one, but you may.
2. do we want to assume that all asgs installations will be using the same ADCIRC/SWAN binaries? This is happening now, but there might be a reason to support asgs installation specific binaries here

Notes:
1. with this change, asgsh is now installed in $HOME/bin and there is one regardless of how many ASGS installs (this is how we should approach it)
2. current changes leverage asgsh's support for profiles, which are really just saved environmental variables that are made available when a profile is "loaded" via asgsh
3. when asgs-brew.pl "installs" asgs, it creates an asgsh profile that contains all environmental variables that are affected by what's happening in asgs-brew.pl; this includes SCRIPTDIR, which takes the value of the asgs directory that was "installed"
4. I need to look to make sure the profile creation is capturing all environmental variables we'd want set, but I think we're pretty close
5. also regarding "saved profiles", only "affected" environmental variables are dumped fully interpolated - (e.g., there is nothing like PATH=$PATH:...); is there value in dumping the entire environment or just affected ones? I was thinking just the affected ones so that anything not directly modified in asgs-brew.pl can still be set outside of asgsh shell and would still be available

**Comment by wwlwpd** [comment]
I decide to make the installation of python consistent with how perlbrew is being used, that is installing it "globally" into $HOME/python27/asgs/build/python-2.7.17 (this reflects perlbrew's directory layout).

**Comment by wwlwpd** [comment]
> We often need to have multiple ASGSes installed on a single user account on an HPC system (e.g., 2019stable for production alongside master or a feature branch). Does asgs-brew accommodate that? Related to that, an HPC user may want to completely uninstall the ASGS, or may have other activities going on the HPC that should not use the custom python and/or perl that the ASGS environment provides, is it possible uninstall the ASGS or temporarily disable the asgs-specific environment?

The ASGS Shell is intended to provide this environment isolation. Also, multiple ASGS installations may be created and managed as profiles in the same shell via the use of profiles. If there is a specific use case or need you'd like me to help set up or expand on, please let me know.

Closing this @jasonfleming - please reopen if you'd like to address any capability that might be missing.
