### ISSUE TITLE
remove ALL conditional env set ups in platforms.sh

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#342]
This may require creating or moving it to exiting mechanisms (like config/operator_defaults.sh) to provide for additional customizations in the asgs shell, but this should be discouraged.

Once we clean up `platforms.sh` we will be in a better position to evaluate the utility of `config/operator_defaults.sh` even being in the repository or move the role of it to the use of a `~/.asgsh_profile` type approach (that should be discouraged).

**Comment by wwlwpd** [comment]
I'd like for the following users to take a look at this and comment: @jasonfleming, @BrianOBlanton, @mattbilskie, @akheir

**Comment by wwlwpd** [comment]
posted in chat:

I’d like:
# `platforms.sh` to be minimal, non-conditional, and very slow changing
# remove config/operators_default.sh from the repo and support something like `$HOME/.asgsh_profile` to mimic how  customization is done normally (again, minimized since most of those parameters should be defaults somewhere if actually needed)
# audit anywhere else these kinds of environmental parameters are set and come up with additional plans (e.g., `config/mesh_defaults.sh`)

**Comment by akheir** [comment]
I also mentioned in chat.

Instead of having one `$HOME/.asgsh_profile` we could have multiple profile which is saved/loaded through asgs shell. In that case we can have different setting per run or we can have one default setting for all same as $HOME/.asgsh_profile

Having multiple settings gives us the flexibility to have different parameters such as different allocation or queue for each run.

**Comment by wwlwpd** [comment]
Note: after thinking about #282, this is kind of clean up is necessary for us to really solve these kinds of differences in the environments

**Comment by jasonfleming** [comment]
Yes, cleaning up platforms.sh is very welcome. Let's strip it down and standardize it .

The config/operator_defaults.sh is basically acting more like documentation at this point and may still have value from that perspective (i.e., convenient storage area for the things that would go into something like ~/.asgsh_profile). 

For controlling which allocation or queue each run will use, I still like using the asgs config files themselves for that, since that is where the other run-specific parameters are set.

**Comment by wwlwpd** [comment]
There is an integration branch (#356) and vetting it will be handled like we handled the ssh config stuff.

1. next activation period, I will run the integration branch (#356).

2. take a poll of current operators about merging it into master before the
activation period after step 1; this will require an early break-in period especially
with the Matlab stuff. So the earlier we do it the better.

3. if in step 2 we choose to not merge it into master, we will bite the bullet after
step 2.
