### ISSUE TITLE
initadcirc to build adcirc v55 which is a tag rather than a branch

### ISSUE THREAD

**Issue by jasonfleming** [jasonfleming/asgs#453]
When building ADCIRC v55 on QueenbeeC I was able to use the v55release-qbc branch successfully. However, when attempting to compile on SuperMIC, I noticed that v55release was not one of the build choices because it is not a branch. Not sure what the best approach is here, can I just use v55release-qbc on any platform? Or do we need to enable the building of tagged versions as well as latest branches?

**Comment by wwlwpd** [comment]
Looks like they deleted `v55release`, which was a branch and have started using tags, `v55.00`. Which is interesting since it indicates the intention to do point releases. E.g., `v55.01`, `v55.09`.

The answer to your question is that tags can be used just like branch names, so rather than checking out `v55release` like we've become accustom, we would want to checkout `v55.00`. This new versioning is better for maintenance, so we just need to know that this is the case.

What remains to be seen is if the minor version `.00` increments past `.09` or if it'll roll into `56.00`. Most software follows the former. I also anticipate this indicates a long term support strategy using a 3rd number after a second `.`. For example, `v55.09.01` - in this case, 55 = major version, 09 = minor version, 01 = point release (stability or critical bug fixes).

**Comment by jasonfleming** [comment]
Ok that makes sense, thank you.

**Comment by wwlwpd** [comment]
@jasonfleming, I created a PR to make this issue more user
friendly. Also set it up for the next iteration, which is
patched "version" support.
